- name: Expense project setup
  hosts: all
  become: yes
  tasks:
    - name: Installing mysql
      ansible.builtin.shell: dnf disable mysql -y

    - name: copy mysql repo name
      ansible.builtin.copy:
        src: mysql.repo
        dest: /etc/yum.repo.d/mysql.repo

    - name: Install mysql server
      ansible.builtin.dnf:
        name: mysql-community-server
        state: present

    - name: start mysql service
      ansible.builtin.systemd:
        name: Restart mysql
        state: restarted
        enabled: yes

    - name: set mysql password
      ansible.builtin.shell: mysql_secure_installation --set-root-pass {{MYSQL_ROOT_PASSWORD}}
