- name: Disable nodejs default version
  ansible.builtin.shell: dnf module disable nodejs -y

- name: Enable nodejs 18 version
  ansible.builtin.shell: dnf module enable nodejs:18 -y

- name: install nodejs
  ansible.builtin.dnf:
    name: nodejs
    state: present

- name: copy backend.service file
  ansible.builtin.copy:
    src: backend.service
    dest: /etc/systemd/system/backend.service

- name: Add application user
  ansible.builtin.user:
    name: expense

- name: Delete app old app dir
  ansible.builtin.file:
    name: /app
    state: absent

- name: Create app dir
  ansible.builtin.file:
    name: /app
    state: directory

- name: Download and extract frontend content
  ansible.builtin.unarchive:
    src: https://expense-artifacts.s3.amazonaws.com/backend.zip
    dest: /app
    remote_src: yes

- name: Download nodejs dependencies
  ansible.builtin.shell: npm install
  args:
    chdir: /app

- name: install mysql client
  ansible.builtin.dnf:
    name: mysql
    state: present

- name: Load the schema
  ansible.builtin.shell: mysql -h mysql-dev.devopspractice1.online -uroot -p{{MYSQL_ROOT_PASSWORD}} < /app/schema/backend.sql

- name: start backend service
  ansible.builtin.systemd:
    name: backend
    state: restarted
    enabled: yes
    daemon_reload: yes