- name: install nginx
  ansible.builtin.dnf:
    name: nginx
    state: present

- name: copy expense.conf
  ansible.builtin.template:
    src: expense.conf
    dest: /etc/nginx/default.d/expense.conf

- name: Import common role for app prerequisite
  ansible.builtin.import_role:
    name: common
    tasks_from: app-prereq
  vars:
    app_dir: /usr/share/nginx/html
    component: frontend

- name: start nginx server
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: yes
